export const CAMBIAR_SECCION = 'CAMBIAR_SECCION';
export const DEFINIR_VUELO = 'DEFINIR_VUELO';
export const DEFINIR_HOSPEDAJE = 'DEFINIR_HOSPEDAJE';
export const DEFINIR_DATOS_COTIZACION = 'DEFINIR_DATOS_COTIZACION';
export const DEFINIR_VALUES = 'DEFINIR_VALUES';
export const RESETEAR_APP = 'RESETEAR_APP';